version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: 'org.spigotmc:spigot-api'
      - dependency-name: 'org.papermc:paper-api'
      - dependency-name: 'net.kyori:adventure-api'