name: Publish

on:
  release:
    types: [ "published" ]
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Fix Gradle Permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        env:
          fad_username: ${{ secrets.REPO_USERNAME }}
          fad_password: ${{ secrets.REPO_PASSWORD }}
        run: ./gradlew publishMavenJavaPublicationToFinallyADecentRepository